#! /bin/sh

# Monitor Settings

bspc monitor -d 1 2 3 4                                                 # Monitor and Workspaces



# Window Settings

bspc config split_ratio          0.55                                   # Main Window Ratio

bspc config borderless_monocle   true                                   # Enable Window Borders
bspc config border_width         0                                      # Window Border Size

bspc config gapless_monocle      false                                  # Enable Window Gaps
bspc config window_gap           10                                     # Window Gap Size



# Auto start applications

openrgb -p White.orp &                                                  # RGB Preset
sxhkd &                                                                 # Keybinds
picom --config $HOME/.config/picom/picom.conf &                         # Compositer
nitrogen --restore &                                                    # Wallpaper
dunst &                                                                 # Notifications
eww open bar &                                                          # Bar
