#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


# Monitor Settings

bspc monitor -d I II III IV                                             #Monitor and Workspaces

bspc config border_width        0                                       # Window Border Size
bspc config window_gap          10                                      # Window Gaps


# Window Settings

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Auto start applications

sxhkd &                                                                 # Keybinds
picom --config $HOME/.config/picom/picom.conf &                         # Compositer
nitrogen --restore &                                                    # Wallpaper
dunst &                                                                 # Notifications
eww open bar &                                                          # Bar
~/.config/eww/scripts/workspaces &                                      # Bar Workspaces
