#! /bin/sh

# Monitor Settings

bspc monitor -d 1 2 3 4                                                 # Monitor and Workspaces
xrandr --output DP-4 --mode 1920x1080 --rate 144                        # Resolution and Refresh Rate


# Window Settings

bspc config split_ratio             0.55                                # Main Window Ratio

bspc config borderless_monocle      true                                # Enable Window Borders
bspc config border_width            0                                   # Window Border Size

bspc config gapless_monocle         false                               # Enable Window Gaps
bspc config window_gap              10                                  # Window Gap Size

bspc config pointer_motion_interval 7ms                                 # Pointer Refresh Interval




# Auto start applications

openrgb -p White.orp &                                                  # RGB Preset
sxhkd &                                                                 # Keybinds
xsetroot -cursor_name left_ptr &                                        # Cursor
picom --config $HOME/.config/picom/picom.conf &                         # Compositer
nitrogen --restore &                                                    # Wallpaper
dunst &                                                                 # Notifications
eww open bar &                                                          # Bar